export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const GET_ALL_ROOMS_REQUEST = 'GET_ALL_ROOMS_REQUEST';
export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_FAIL = 'GET_ALL_ROOMS_FAIL';

export const GET_ROOM_MESSAGES = 'GET_ROOM_MESSAGES';
export const GET_ROOM_MESSAGES_REQUEST = 'GET_ROOM_MESSAGES_REQUEST';
export const GET_ROOM_MESSAGES_SUCCESS = 'GET_ROOM_MESSAGES_SUCCESS';
export const GET_ROOM_MESSAGES_FAIL = 'GET_ROOM_MESSAGES_FAIL';

export const POST_CREATE_ROOM = 'POST_CREATE_ROOM';
export const POST_CREATE_ROOM_REQUEST = 'POST_CREATE_ROOM_REQUEST';
export const POST_CREATE_ROOM_SUCCESS = 'POST_CREATE_ROOM_SUCCESS';
export const POST_CREATE_ROOM_FAIL = 'POST_CREATE_ROOM_FAIL';